server:
 port: 8080
 context-path: /huobaibai
  
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: myboot
    password: boot
